version: '3'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: /dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: usersdb
    ports: 
      - 3306:3306
    networks:
      - authnetwork
  
  lb4:
    build: ./m1_dweb
    ports: 
      - 8000:8000
    depends_on:
      - mysql
    networks:
      - authnetwork
networks:
  authnetwork: